name: Maven Package

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
      env:
        ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'

    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests

    - name: Commit .JAR file
      run: |
        git config --global user.name "Suhas Bk"
        git config --global user.email "kowligi1998@gmail.com"
        git config --global credential.helper cache
        git clone https://${{secrets.ACCESS_TOKEN}}@github.com/SuhasBk/epapers
        cp target/*.jar epapers/JAR/epapers.jar
        cd epapers
        git add JAR/*.jar
        git commit -m "JAR package"
        git push
